"""add profile cache and oauth tokens

Revision ID: 43ecbe64c666
Revises: 274dcbf77d84
Create Date: 2026-05-16 10:24:06.501320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "43ecbe64c666"
down_revision: Union[str, Sequence[str], None] = "274dcbf77d84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_provider_enum = postgresql.ENUM(
        "GITHUB",
        "HUGGING_FACE",
        name="oauth_provider",
    )
    oauth_provider_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "GITHUB",
                "HUGGING_FACE",
                name="oauth_provider",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("encrypted_access_token", sa.Text(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "provider", name="uq_oauth_token_profile_provider"
        ),
    )
    op.add_column(
        "external_urls", sa.Column("parsed_repo_list", sa.JSON(), nullable=True)
    )
    op.add_column(
        "external_urls", sa.Column("parsed_commit_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "external_urls", sa.Column("parsed_hf_model_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "external_urls",
        sa.Column("parsed_hf_dataset_count", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_urls", "parsed_hf_dataset_count")
    op.drop_column("external_urls", "parsed_hf_model_count")
    op.drop_column("external_urls", "parsed_commit_count")
    op.drop_column("external_urls", "parsed_repo_list")
    op.drop_table("oauth_tokens")
    postgresql.ENUM(name="oauth_provider").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
