"""user changed to mapped columns

Revision ID: 4eebe9389c7c
Revises: ea09e65a3dc3
Create Date: 2026-05-10 06:28:04.537237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eebe9389c7c'
down_revision: Union[str, Sequence[str], None] = 'ea09e65a3dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
