"""added dev application table

Revision ID: 57a9738a070a
Revises: 194f1dd05751
Create Date: 2026-05-29 05:22:06.611635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a9738a070a'
down_revision: Union[str, Sequence[str], None] = '194f1dd05751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_applications_id'), 'developer_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_developer_applications_id'), table_name='developer_applications')
    op.drop_table('developer_applications')
    # ### end Alembic commands ###
