"""add profile and related models

Revision ID: 63ca15a34c6f
Revises: b341fd949379
Create Date: 2026-05-12 12:16:41.731820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ca15a34c6f'
down_revision: Union[str, Sequence[str], None] = 'b341fd949379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('CORE', 'SPECIALIZED', name='role_tier'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_hidden_full_name', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_hidden_age', sa.Boolean(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('is_hidden_years_experience', sa.Boolean(), nullable=False),
    sa.Column('last_ai_analysis', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('education_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('degree', sa.Enum('PHD', 'MASTERS', 'BACHELORS', 'HIGH_SCHOOL', 'OTHER', name='degree_type'), nullable=False),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('GITHUB', 'HUGGING_FACE', 'LINKEDIN', 'OTHER', name='external_url_type'), nullable=False),
    sa.Column('url_str', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'OAUTH_LINKED', name='external_url_source'), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('skill_score', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skill_level'), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'role_id', name='uq_profile_role')
    )
    op.create_table('profile_skill_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['skill_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'tag_id', name='uq_profile_tag')
    )
    op.create_table('project_history_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('technologies_used', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_history_entries')
    op.drop_table('profile_skill_tags')
    op.drop_table('profile_roles')
    op.drop_table('external_urls')
    op.drop_table('education_entries')
    op.drop_table('profiles')
    op.drop_table('skill_tags')
    op.drop_table('roles')
    # ### end Alembic commands ###
