"""add external url parse status

Revision ID: 6fa3ae0f2fc3
Revises: 43ecbe64c666
Create Date: 2026-05-16 10:33:07.679358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6fa3ae0f2fc3"
down_revision: Union[str, Sequence[str], None] = "43ecbe64c666"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    external_url_parse_status = sa.Enum(
        "PENDING", "SUCCESS", "FAILED", name="external_url_parse_status"
    )
    external_url_parse_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "external_urls",
        sa.Column(
            "parse_status",
            external_url_parse_status,
            nullable=False,
            server_default="PENDING",
        ),
    )
    op.add_column("external_urls", sa.Column("parse_message", sa.Text(), nullable=True))
    op.add_column("external_urls", sa.Column("parsed_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint(
        "uq_external_url_profile_type",
        "external_urls",
        ["profile_id", "type"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_external_url_profile_type", "external_urls", type_="unique")
    op.drop_column("external_urls", "parsed_at")
    op.drop_column("external_urls", "parse_message")
    op.drop_column("external_urls", "parse_status")
    sa.Enum(name="external_url_parse_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
