"""add additional fields to unregistered member

Revision ID: 888360ed6519
Revises: 57a9738a070a
Create Date: 2026-05-29 14:18:59.511558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888360ed6519'
down_revision: Union[str, Sequence[str], None] = '57a9738a070a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_external_url_profile_type', 'external_urls', ['profile_id', 'type'])
    op.add_column('team_members', sa.Column('unregistered_role_name', sa.String(), nullable=True))
    op.add_column('team_members', sa.Column('unregistered_skill_level', sa.String(), nullable=True))
    op.add_column('team_members', sa.Column('unregistered_skill_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'unregistered_skill_score')
    op.drop_column('team_members', 'unregistered_skill_level')
    op.drop_column('team_members', 'unregistered_role_name')
    op.drop_constraint('uq_external_url_profile_type', 'external_urls', type_='unique')
    # ### end Alembic commands ###
