"""add assigned_role to team_members

Revision ID: 9a8b7c6d5e4f
Revises: 888360ed6519
Create Date: 2026-05-31 13:19:37.611456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9a8b7c6d5e4f"
down_revision: Union[str, Sequence[str], None] = "888360ed6519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_members", sa.Column("assigned_role", sa.String(), nullable=True)
    )

    # op.execute(
    #     "UPDATE team_members SET assigned_role = unregistered_role_name "
    #     "WHERE assigned_role IS NULL AND unregistered_role_name IS NOT NULL"
    # )

    # op.execute("""
    #     UPDATE team_members tm
    #     SET assigned_role = (
    #         SELECT o.proposed_role
    #         FROM offers o
    #         WHERE o.team_id = tm.team_id
    #           AND o.recipient_id = tm.user_id
    #           AND o.status = 'accepted'
    #         ORDER BY COALESCE(o.responded_at, o.created_at) DESC
    #         LIMIT 1
    #     )
    #     WHERE tm.assigned_role IS NULL
    #       AND tm.user_id IS NOT NULL
    #       AND EXISTS (
    #           SELECT 1
    #           FROM offers o
    #           WHERE o.team_id = tm.team_id
    #             AND o.recipient_id = tm.user_id
    #             AND o.status = 'accepted'
    #       )
    #     """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_members", "assigned_role")
    # ### end Alembic commands ###
